data class MemoryInfo(
    val total: String = "0 B",
    val free: String = "0 B",
    val available: String = "0 B",
    val used: String = "0 B",
    val usagePercent: Float = 0f,
    val buffers: String = "0 B",
    val cached: String = "0 B",
    val swapCached: String = "0 B",
    val active: String = "0 B",
    val inactive: String = "0 B",
    val activeAnon: String = "0 B",
    val inactiveAnon: String = "0 B",
    val activeFile: String = "0 B",
    val inactiveFile: String = "0 B",
    val swapTotal: String = "0 B",
    val swapFree: String = "0 B",
    val swapUsed: String = "0 B",
    val swapUsagePercent: Float = 0f,
    val anonPages: String = "0 B",
    val mapped: String = "0 B",
    val shmem: String = "0 B",
    val slab: String = "0 B",
    val kernelStack: String = "0 B",
    val pageTables: String = "0 B",
    val vmallocUsed: String = "0 B"
) 